import { AppNav } from "@/components/lemmy/app-nav";
import { ThemeProvider } from "@/components/ui/theme";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/lemmy/query-provider";
import { Provider } from "react-wrap-balancer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <QueryProvider>
            <Provider>
              <div className="h-screen">
                <AppNav />
                {children}
              </div>
            </Provider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
