import { Body, Footer, Header, Layout } from "@/components/ui/layout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppNav } from "@/components/lemmy/app-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Header>
            <AppNav />
          </Header>
          <Body>{children}</Body>
          {/* <Footer></Footer> */}
        </Layout>
      </body>
    </html>
  );
}
